version: '2'
services:
  web1:
   #build: ./Docker_main
   image: image_name
   ports:
    - 5000:8080
   #volumes: 
   # - ./web_files:/usr/local/tomcat/webapps/webapp
   volumes:
    - ./Docker_main:/usr/local/tomcat/folder 
  web2:
    #build: ./Docker_result
    image: image_name
    ports:
     - "5001:80"
    depends_on:
     - web1
